"use client";
import { useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { hardenDetector, searchAdversarial } from "@/lib/api/closed-loop";

export default function ClosedLoopPage(){
 const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<any>(null); const [findings,setFindings]=useState<any>(null);
 const run=async()=>{if(loading)return;setLoading(true);setError("");try{const config={events:1000,seed:829134,attack_ids:null,fraud_rate:.15,difficulty:"very-high" as const,adaptation:"adversarial" as const,noise:"medium" as const,threshold:.5};const [h,s]=await Promise.all([hardenDetector(config),searchAdversarial(config)]);setResult(h);setFindings(s);}catch(e){setError(e instanceof Error?e.message:"Closed-loop run failed");}finally{setLoading(false)}};
 const roundMetrics=(round:any)=>round?.metrics??round??{};
 const finalMetrics=roundMetrics(result?.rounds?.at(-1));
 return <AppShell title="The Closed Loop"><div className="page-container"><div className="page-head"><div><p className="eyebrow">CONTINUOUS ADVERSARIAL HARDENING · LIVE BACKEND</p><h1>The Closed-Loop AI Defense Engine</h1><p className="subtitle">Real synthetic red-team search followed by blue-team hardening and untouched-test evaluation.</p></div><div className="head-actions"><Link href="/detection-lab" className="date-select">Detection Lab →</Link><button className="primary" onClick={run} disabled={loading}>{loading?"Running Red → Blue Loop…":"⚔ Run Closed-Loop Experiment"}</button></div></div>
 {error&&<div className="panel" style={{padding:14,marginBottom:16,color:"#ff819c"}}>{error}</div>}
 <div className="closed-loop-hero" style={{marginBottom:20}}><div><strong>Identify → Generate → Defend → Learn → Mutate</strong><span>Synthetic-only adversarial evaluation.</span></div><div className="loop-steps">{["IDENTIFY","GENERATE","DEFEND","LEARN","MUTATE"].map((x,i)=><div key={x} className="loop-node active"><strong>{i+1}. {x}</strong><span>{i===4?"Harder variants":"Backend stage"}</span></div>)}</div></div>
 {!result?<div className="panel attack-empty"><span>◌</span><h3>Ready to stress-test the detector</h3><p>Run the experiment to search synthetic blind spots and harden the model.</p></div>:<><div className="metric-grid metric-grid-three" style={{marginBottom:20}}>{[["Baseline F1",result.baseline?.f1],["Final F1",finalMetrics.f1],["Untouched Test",result.untouched_test_events]].map(([k,v])=><div className="panel" style={{padding:16}} key={k as string}><span style={{fontSize:9,color:"#8a97ae"}}>{k}</span><strong style={{display:"block",fontSize:24,marginTop:6}}>{typeof v==="number"&&v<=1?(v*100).toFixed(1)+"%":String(v)}</strong></div>)}</div><div className="responsive-split responsive-split-balanced"><section className="panel" style={{padding:18}}><div className="panel-head"><div><h2>Hardening Rounds</h2><p>Each round is evaluated on the isolated test set.</p></div></div><div style={{display:"grid",gap:10,marginTop:12}}>{(result.rounds||[]).map((r:any)=>{const m=roundMetrics(r);return <div key={r.round} style={{padding:12,border:"1px solid #263650",borderRadius:8,background:"#0b1321"}}><div style={{display:"flex",justifyContent:"space-between"}}><strong>ROUND {r.round}</strong><span className="badge badge-green">F1 {(Number(m.f1||0)*100).toFixed(1)}%</span></div><small style={{color:"#8a97ae"}}>Precision {(Number(m.precision||0)*100).toFixed(1)}% · Recall {(Number(m.recall||0)*100).toFixed(1)}% · FPR {(Number(m.false_positive_rate||0)*100).toFixed(2)}%</small></div>})}</div></section><section className="panel" style={{padding:18}}><div className="panel-head"><div><h2>Red-Team Findings</h2><p>Lowest-confidence synthetic variants selected for further evaluation.</p></div></div><div style={{display:"grid",gap:8,marginTop:12}}>{(findings?.findings||[]).slice(0,8).map((f:any,i:number)=><div key={i} style={{padding:10,border:"1px solid #2b354d",borderRadius:7}}><strong>{f.attack_id||f.attack_family||"Synthetic variant"}</strong><div style={{fontSize:9,color:"#8a97ae",marginTop:3}}>{Object.entries(f).filter(([k])=>!['attack_id','attack_family'].includes(k)).slice(0,3).map(([k,v])=>`${k}: ${String(v)}`).join(" · ")}</div></div>)}</div></section></div></>}
 </div></AppShell>;
}
