"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { attacks } from "@/data/attacks";
import type { Attack } from "@/types/attack";
import { AttackCard } from "./AttackCard";
import { AttackFilters, blankFilters, type Filters } from "./AttackFilters";
import { AttackLandscape } from "./AttackLandscape";
import { AttackTable } from "./AttackTable";

const includes = (source: string[], values: string[]) => !values.length || values.some(value => source.includes(value));
export function AttackLibraryClient() {
  const [rawSearch,setRawSearch]=useState(""); const [search,setSearch]=useState(""); const [filters,setFilters]=useState<Filters>(blankFilters); const [view,setView]=useState<"grid"|"table">("grid"); const [sort,setSort]=useState("severity"); const [collapsed,setCollapsed]=useState(false); const [selected,setSelected]=useState<Attack|undefined>(); const [visible,setVisible]=useState(9);
  useEffect(()=>{const timer=setTimeout(()=>setSearch(rawSearch),250);return()=>clearTimeout(timer)},[rawSearch]);
  const filtered = useMemo(()=>attacks.filter(attack=>{ const haystack=[attack.id,attack.name,attack.description,attack.category,...attack.paymentRails,...attack.aiCapabilities,...attack.target,...attack.defenseStrategy].join(" ").toLowerCase(); return (!search || haystack.includes(search.toLowerCase())) && includes([attack.category],filters.categories) && includes(attack.paymentRails,filters.rails) && includes(attack.aiCapabilities,filters.ai) && includes([attack.severity],filters.severity) && includes([attack.evidenceStatus],filters.evidence) && includes([attack.simulationStatus],filters.simulation) && includes([attack.difficulty],filters.difficulty);}),[search,filters]);
  const ordered = useMemo(() => [...filtered].sort((a,b) => sort === "alphabetical" ? a.name.localeCompare(b.name) : sort === "simulation" ? a.simulationStatus.localeCompare(b.simulationStatus) : sort === "evidence" ? a.evidenceStatus.localeCompare(b.evidenceStatus) : ({critical:4,high:3,medium:2,low:1}[b.severity] - {critical:4,high:3,medium:2,low:1}[a.severity])),[filtered,sort]);
  const kpis=[{label:"Attack vectors identified",value:attacks.length,detail:"+6 this month",tone:"purple"},{label:"Payment rails covered",value:new Set(attacks.flatMap(a=>a.paymentRails)).size,detail:"UPI · Cards · Wallets · RTGS…",tone:"blue"},{label:"Attacks with real precedent",value:attacks.filter(a=>a.evidenceStatus==="documented").length,detail:`${Math.round(attacks.filter(a=>a.evidenceStatus==="documented").length/attacks.length*100)}% documented in library`,tone:"green"},{label:"Simulation ready",value:attacks.filter(a=>a.simulationStatus==="ready").length,detail:`${Math.round(attacks.filter(a=>a.simulationStatus==="ready").length/attacks.length*100)}% of identified attacks`,tone:"amber"}];
  return <>
    <div className="library-page-head"><div><p className="eyebrow">SECURITY OPERATIONS CENTER</p><h1>Attack Library</h1><p className="subtitle">Threat intelligence across emerging AI-powered payment fraud</p></div><div className="library-actions"><label className="attack-search"><span>⌕</span><input value={rawSearch} onChange={event=>setRawSearch(event.target.value)} placeholder="Search attacks, rails, techniques…"/></label><button className="filter-button" onClick={()=>setCollapsed(!collapsed)}>☷ Filters</button><Link className="primary" href={selected ? `/simulator?attack=${selected.id}` : "/simulator"}>Launch Simulation <span>→</span></Link></div></div>
    <div className="library-kpis">{kpis.map(kpi=><section className="library-kpi panel" key={kpi.label}><span className={`library-kpi-icon ${kpi.tone}`}>{kpi.tone==="purple"?"◈":kpi.tone==="blue"?"◎":kpi.tone==="green"?"✓":"ϟ"}</span><div><p>{kpi.label}</p><h2>{kpi.value}</h2><span>{kpi.detail}</span></div></section>)}</div>
    <div className="library-workspace"><AttackFilters filters={filters} onChange={setFilters} collapsed={collapsed} onToggle={()=>setCollapsed(!collapsed)}/><div className="attack-intelligence"><AttackLandscape attacks={filtered} selectedId={selected?.id} onSelect={attack=>setSelected(attack)}/><section className="panel attack-collection"><div className="collection-head"><div><h2>Attack intelligence <span>{filtered.length}</span></h2><p>{selected ? <><b>{selected.id}</b> selected in landscape</> : "Browse and inspect your threat taxonomy"}</p></div><div className="collection-controls"><select aria-label="Sort attack list" value={sort} onChange={event => setSort(event.target.value)}><option value="severity">Severity: high to low</option><option value="alphabetical">Alphabetical</option><option value="simulation">Simulation readiness</option><option value="evidence">Evidence status</option></select><div className="view-toggle"><button className={view==="grid"?"active":""} onClick={()=>setView("grid")}>▦ Grid</button><button className={view==="table"?"active":""} onClick={()=>setView("table")}>☷ Table</button></div></div></div>
      {filtered.length ? view === "grid" ? <><div className="attack-grid">{ordered.slice(0,visible).map(attack=><AttackCard key={attack.id} attack={attack}/>)}</div>{visible < filtered.length && <button className="load-more" onClick={()=>setVisible(v=>v+9)}>Load more intelligence</button>}</> : <AttackTable attacks={filtered}/> : <div className="attack-empty"><span>◌</span><h3>No attacks match these filters</h3><p>Try clearing a filter or searching a broader term.</p><button onClick={()=>{setFilters(blankFilters);setRawSearch("")}}>Clear filters</button></div>}
    </section></div></div>
  </>;
}
