"use client";

import Link from "next/link";
import { useState } from "react";
import { attacks, categoryLabel, simulationProfiles } from "@/data/attacks";
import type { Attack } from "@/types/attack";
import { Badge } from "./AttackCard";

const tabs = ["Overview", "Evidence", "Lifecycle", "Signals", "Defense", "Simulation"] as const;
const labels: Record<string,string> = { documented:"Documented",emerging:"Observed / Emerging",research:"Research-stage",hypothetical:"Hypothetical",ready:"Simulation ready","in-development":"In development","research-only":"Research only","not-simulated":"Not simulated" };
export function AttackDetailClient({ attack }: { attack: Attack }) {
  const [tab,setTab]=useState<typeof tabs[number]>("Overview"); const profile=simulationProfiles.find(item=>item.attackId===attack.id); const related=attacks.filter(item=>attack.relatedAttackIds.includes(item.id));
  return <div className="attack-detail-page"><Link href="/attack-library" className="back-link">← Back to library</Link><header className="detail-title"><div><span className="attack-id">{attack.id}</span><h1>{attack.name}</h1><p>{categoryLabel[attack.category]} · {attack.paymentRails.join(" · ")}</p><div className="detail-badges"><Badge value={attack.severity} kind="severity"/><Badge value={attack.evidenceStatus} kind="evidence"/><Badge value={attack.simulationStatus} kind="simulation"/></div></div><div className="detail-actions"><Link href={`/investigation?attack=${attack.id}`}>Add to investigation</Link><Link className="primary" href={`/simulator?attack=${attack.id}`}>Launch Simulation <span>→</span></Link></div></header>
    <nav className="detail-tabs" aria-label="Attack intelligence sections">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?"active":""}>{item}</button>)}</nav>
    {(tab === "Overview" || tab === "Lifecycle") && <section className="detail-section"><div className="section-title"><span>01</span><div><h2>Attack Overview</h2><p>{attack.description}</p></div></div><div className="overview-stats"><Stat label="Primary target" value={attack.target.join(" · ")}/><Stat label="Payment rails" value={attack.paymentRails.join(" / ")}/><Stat label="Financial impact" value={attack.financialImpact}/><Stat label="Scalability" value={attack.scalability || attack.scalabilityScore || "High"}/><Stat label="Detection difficulty" value={attack.detectionDifficulty}/><Stat label="AI capability" value={attack.aiCapabilities.join(" + ")}/></div></section>}
    {(tab === "Overview" || tab === "Lifecycle") && <section className="detail-section"><div className="section-title"><span>02</span><div><h2>Attack lifecycle</h2><p>High-level threat lifecycle for analyst context, not an operational playbook.</p></div></div><div className="lifecycle">{attack.lifecycle.map((step,index)=><div className="lifecycle-step" key={step.step}><span>{String(step.step).padStart(2,"0")}</span><div><b>{step.title}</b><p>{step.description}</p></div>{index < attack.lifecycle.length-1 && <i>→</i>}</div>)}</div></section>}
    {(tab === "Overview" || tab === "Evidence") && <section className="detail-section"><div className="section-title"><span>03</span><div><h2>Real-World Evidence</h2><p>Evidence is intentionally distinguished from emerging and research-stage entries.</p></div></div><div className="evidence-list">{attack.evidence.map((item,index)=><article key={index} className="evidence"><div><Badge value={attack.evidenceStatus} kind="evidence"/><span>{item.sourceType}</span></div><h3>{item.title}</h3><p>{item.publisher}{item.publicationDate ? ` · ${item.publicationDate}` : ""}</p><blockquote>{item.summary}</blockquote>{item.url && <a href={item.url} target="_blank" rel="noreferrer">Open reference ↗</a>}</article>)}</div></section>}
    {(tab === "Overview" || tab === "Signals") && <section className="detail-section"><div className="section-title"><span>04</span><div><h2>Observable Payment Behavior</h2><p>The Red Team → Blue Team bridge: measurable signals an analyst or model can evaluate.</p></div></div><div className="signals">{attack.observableSignals.map((signal,index)=><span key={signal}><b>{String(index+1).padStart(2,"0")}</b>{signal}</span>)}</div><div className="genai-compare"><h3>Why GenAI changes this attack</h3><div><p><b>Traditional</b>Manual impersonation · generic contact · slower iteration</p><p><b>GenAI-assisted</b>Automated personalization · broader reach · rapid adaptation</p></div><footer><span>Scale ↑</span><span>Personalization ↑</span><span>Cost ↓</span><span>Adaptability ↑</span></footer></div></section>}
    {(tab === "Overview" || tab === "Defense") && <section className="detail-section"><div className="section-title"><span>05</span><div><h2>Blue Team Defense</h2><p>Risk-control workflow; mitigation decisions remain context-dependent.</p></div></div><div className="defense-flow"><div><b>Attack</b><span>{attack.name}</span></div><i>→</i><div><b>Observable behavior</b><span>{attack.observableSignals.slice(0,2).join(" · ")}</span></div><i>→</i><div><b>Detection strategy</b><span>{attack.defenseStrategy.join(" · ")}</span></div><i>→</i><div><b>Risk controls</b><span>Step-up verification · Hold · Analyst review</span></div></div></section>}
    {(tab === "Overview" || tab === "Simulation") && <section className="detail-section" id="simulation"><div className="section-title"><span>06</span><div><h2>Simulation Profile</h2><p>{profile ? "This profile is ready to pass into the Red Team Simulator." : "Simulation is not currently available for this research track."}</p></div></div>{profile ? <div className="simulation-profile"><Stat label="Generator" value={profile.generatorId}/><Stat label="Feature count" value={String(profile.generatedFeatures.length)}/><Stat label="Dataset status" value="Ready"/><Stat label="Maximum volume" value={`${(profile.maxVolume/1000000).toFixed(0)}M+`}/><Stat label="Generator version" value={profile.version}/><Link className="primary" href={`/simulator?attack=${attack.id}`}>Launch Simulation →</Link></div> : <div className="simulation-unavailable"><b>Simulation not available</b><span>This attack is currently {labels[attack.simulationStatus]}.</span></div>}</section>}
    <section className="detail-section related-section"><div className="section-title"><span>07</span><div><h2>Related Attack Chain</h2><p>Multi-stage campaigns can link tactics across the threat library.</p></div></div><div className="attack-chain">{[attack,...related].map((item,index)=><div key={item.id}>{index>0&&<i>→</i>}<Link href={`/attack-library/${item.id}`}><span>{item.id}</span>{item.name}</Link></div>)}</div></section>
  </div>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="detail-stat"><span>{label}</span><b>{value}</b></div>}
