"use client";
import { useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { detectSimulation } from "@/lib/api/detection";

export default function DetectionLabPage() {
  const [threshold,setThreshold]=useState(50); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<any>(null);
  const run = async () => { setLoading(true); setError(""); try { setResult(await detectSimulation({events:5000,seed:829134,attack_ids:null,fraud_rate:.15,difficulty:"very-high",adaptation:"adaptive",noise:"medium",threshold:threshold/100})); } catch(e){setError(e instanceof Error?e.message:"Detection failed");} finally{setLoading(false);} };
  const m=result?.metrics;
  return <AppShell title="Blue Team Detection Lab"><div className="page-container">
    <div className="page-head"><div><p className="eyebrow">BLUE TEAM DETECTION BENCHMARK · LIVE BACKEND</p><h1>AI Payment Defense & Detection Lab</h1><p className="subtitle">Threshold tuning and evaluation against the actual synthetic payment generator.</p></div><div className="head-actions"><Link href="/closed-loop" className="primary">Attack the Detector →</Link></div></div>
    {error && <div className="panel" style={{padding:14,marginBottom:16,color:"#ff819c"}}>{error}</div>}
    <section className="panel" style={{padding:18,marginBottom:18}}><div className="panel-head"><div><h2>Decision Threshold</h2><p>Changes the actual detector operating point.</p></div><strong style={{fontFamily:"DM Mono",fontSize:22,color:"#8f82ff"}}>{threshold}%</strong></div><input type="range" min="20" max="90" value={threshold} onChange={e=>setThreshold(+e.target.value)} style={{width:"100%"}}/><div style={{display:"flex",justifyContent:"space-between",fontSize:9,color:"#7d8aa0",marginTop:6}}><span>HIGH SENSITIVITY</span><span>LOW FRICTION</span></div><button className="primary" style={{marginTop:14}} onClick={run} disabled={loading}>{loading?"Running evaluation…":"Run Backend Evaluation"}</button></section>
    {m && <><div className="metric-grid metric-grid-six" style={{marginBottom:18}}>{[["F1",m.f1], ["Precision",m.precision], ["Recall",m.recall], ["ROC-AUC",m.roc_auc], ["PR-AUC",m.pr_auc], ["FPR",m.false_positive_rate]].map(([k,v])=><div className="panel" style={{padding:14,textAlign:"center"}} key={k as string}><span style={{fontSize:9,color:"#8a97ae"}}>{k}</span><h2 style={{margin:"6px 0",fontSize:22}}>{(Number(v)*100).toFixed(1)}%</h2></div>)}</div><div className="responsive-split responsive-split-balanced"><section className="panel" style={{padding:18}}><div className="panel-head"><div><h2>Confusion Matrix</h2><p>Actual counts from the held-out test population.</p></div></div><div className="confusion-matrix"><div className="matrix-quad tp"><span>TP</span><strong>{m.true_positives}</strong></div><div className="matrix-quad fp"><span>FP</span><strong>{m.false_positives}</strong></div><div className="matrix-quad fn"><span>FN</span><strong>{m.false_negatives}</strong></div><div className="matrix-quad tn"><span>TN</span><strong>{m.true_negatives}</strong></div></div></section><section className="panel" style={{padding:18}}><div className="panel-head"><div><h2>Performance by Attack Family</h2><p>Model behavior across the threat taxonomy.</p></div></div><div style={{display:"grid",gap:8,marginTop:12}}>{Object.entries(result.by_family||{}).map(([family,stats]:any)=><div key={family} style={{display:"grid",gridTemplateColumns:"1fr 80px",gap:12,alignItems:"center"}}><span>{family}</span><strong style={{fontFamily:"DM Mono"}}>{(stats.f1*100).toFixed(1)}%</strong></div>)}</div></section></div></>}
  </div></AppShell>;
}
